
package org.mybatis.generator.api;

import org.mybatis.generator.api.dom.java.CompilationUnit;
import org.mybatis.generator.config.Context;

/**
 * Objects implementing this interface are used to convert the internal 
 * representation of the Java DOM classes into a string suitable for
 * saving to the file system.  Note that the string generated by this
 * class will be saved directly to the file system with no additional modifications.
 * 
 * <p>Only one instance of the class will be created in each context.  Configuration can
 * be passed into the class through the use of properties in the Context.
 * 
 * @author Jeff Butler
 *
 */
public interface JavaFormatter {
    void setContext(Context context);

    String getFormattedContent(CompilationUnit compilationUnit);
}
